config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes, except: %i[show]
  resources :sessions, only: %i[create destroy]
  resources :users, only: %i[new create]

  get :login, to: 'users#login', as: :login
  get :logout, to: 'sessions#destroy', as: :logout

  root to: 'notes#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  MAX_TITLE_LENGTH = 30
  MAX_BODY_LENGTH = 1000

  belongs_to :user

  validates :title, presence: true, length: {maximum: MAX_TITLE_LENGTH}
  validates :body, length: {maximum: MAX_BODY_LENGTH}

  before_validation :check_title, :check_body

  def check_title
    self.title = title.truncate(MAX_TITLE_LENGTH) if title && title.length > MAX_TITLE_LENGTH
    self.title = body.truncate(MAX_TITLE_LENGTH) if title.blank? && body
  end

  def check_body
    self.body = body.truncate(MAX_BODY_LENGTH) if body && body.length > MAX_BODY_LENGTH
  end

  ##
  # Class Methods
  ##

  def self.search(search_term)
    Note.where("lower(title) LIKE :search OR lower(body) LIKE :search", search: "%#{search_term.downcase}%")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :notes, dependent: :destroy

  validates :email, presence: true, uniqueness: {case_sensitive: false}

  before_save :normalize_email

  def normalize_email
    self.email = email.downcase if email
  end

  def proper_name
    name.titleize
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authorize_user

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id]) unless session[:user_id].nil?
  end

  def logged_in?
    !current_user.nil?
  end

  def authorize_user
    redirect_to "/login" unless logged_in?
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_note, only: %i[edit update destroy]

  def index
    search = params.has_key?(:search)
    @notes = current_user.notes

    if search
      @search_pattern = params[:search]
      @notes = @notes.search(params[:search])
    end

    @notes = @notes.order(updated_at: :desc)
  end

  def new
    @note = current_user.notes.new
  end

  def edit; end

  def create
    @note = current_user.notes.new(note_params)

    if @note.save
      redirect_to root_url, notice: "Note was successfully created."
    else
      render :new
    end
  end

  def update
    if @note.update(note_params)
      redirect_to root_url, notice: "Note was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to root_url, notice: "Note was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = current_user.notes.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def note_params
    params.require(:note).permit(:title, :body, :search)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorize_user, only: [:create]

  def create
    user = User.find_by(email: params[:user][:email].downcase)&.authenticate(params[:user][:password])

    if user
      session[:user_id] = user.id
      redirect_back(fallback_location: root_url)
    else
      redirect_to login_url, alert: "Login Incorrect"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "You have been logged out"
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authorize_user, only: %i[create login]

  def create
    if User.find_by(email: params[:user][:email].downcase)
      redirect_to login_url, alert: "User already exists, please log in"
      return
    end

    @user = User.create user_params

    if @user.valid?
      session[:user_id] = @user.id
      redirect_to root_url
    else
      redirect_to login_url(register: true), alert: "Invalid Credentials Provided"
    end
  end

  def login
    if logged_in?
      redirect_to root_url
      return
    end

    @user = User.new
    @login_form = params[:register].to_s.downcase == "true" ? "registration_form" : "login_form"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |type, msg| %>
      <div class="flash <%= 'flash-' + type %>">
        <%= msg %>
      </div>
    <% end %>
    <section id="header">
      <%= render "header" %>
    </section>
    <section id="body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true, data: { max_length: Note::MAX_TITLE_LENGTH } %>
    <div id="title-remaining-count"></div>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, data: { max_length: Note::MAX_BODY_LENGTH } %>
    <div id="body-remaining-count"></div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_header.html.erb
<div class="welcome-msg">
  <h1>Welcome <%= current_user.proper_name %></h1>
  <div class="logout">
    Not you? <%= link_to :logout, logout_path %>
  </div>
</div>

app/views/notes/_note.html.erb
<div class="note">
  <%= link_to "edit", edit_note_path(note), class: "material-icons controls note-edit" %>
  <div class="title"><%= note.title %></div>
  <div class="body"><%= simple_format(note.body) %></div>
  <div class="footer">Last updated on <%= note.updated_at.strftime("%b %d, %Y @ %I:%M %p") %> by <%= note.user.proper_name %></div>
  <%= link_to "delete_forever", note, method: :delete, data: { confirm: "Are you sure?" }, class: "material-icons controls note-destroy" %>
</div>

app/views/notes/_search_bar.html.erb
<%= form_tag root_path, method: :get do %>
  <div class="search-bar-group">
    <%= link_to "X", root_url, class: 'search-clear-btn' %>
    <%= text_field_tag :search, params[:search], placeholder: "Search", class: "search-field" %>
    <%= submit_tag "search", name: nil, class: 'material-icons search-btn' %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>
<%= render "form", note: @note %>
<%= link_to "Back", root_path %>

app/views/notes/index.html.erb
<section id="notes">
  <%= render "search_bar" %>
  <%= button_to "New Note", new_note_path, method: :get, id: "new-note", class: "lg-only"%>
  <%= button_to "+", new_note_path, method: :get, id: "new-note", class: "sm-only"%>
  <% if @notes.empty? %>
    <% if @search_pattern %>
      <div id="empty-note">
        Sorry, but no notes match "<%= @search_pattern %>"... <%= link_to "please try another search term", root_url %>
      </div>
    <% else %>
      <div id="empty-note">
        Doesn"t look like you have any notes yet
        <div class="add-note"><%= link_to "why not add one?", new_note_path %></div>
      </div>
    <% end %>
  <% end %>
  <% @notes.each do |note| %>
    <%= render "note", note: note %>
  <% end %>
</section>
<section id="footer">
  <div class="notes-count">
    <% if @notes.count > 0 %>
      <%= pluralize @notes.count, 'notes' %> found
    <% else %>
      no notes found
    <% end %>
  </div>
</section>

app/views/notes/new.html.erb
<section id="note-form">
  <h1>New Note</h1>
  <%= render "form", note: @note %>
  <%= link_to "Back", root_path %>
</section>

app/views/users/_header.html.erb
<div class="login-msg">
  <h2>Please <%= @login_form == "login_form" ? "Log In" : "Register" %></h2>
</div>

app/views/users/_login_form.html.erb
<section id="login-form">
  <%= form_with(model: @user, local: true, url: {controller: 'sessions', action: 'create'}) do |form|%>
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, autofocus: true %>
    </div>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div class="actions">
      <%= form.submit 'Login' %>
    </div>
  <%end%>
  <p>If you don't have an account, please <%= link_to 'Register', login_path(register: true)%></p>
</div>

app/views/users/_registration_form.html.erb
<section id="login-form">
  <%= form_with(model: @user, local: true, url: {action: 'create'}) do |form|%>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, autofocus: true %>
    </div>
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= form.submit 'Register' %>
    </div>
  <%end%>
  <p>If you already have an account, please <%= link_to 'Login', login_path(register: false)%></p>
</section>

app/views/users/login.html.erb
<!-- We render here so we can pick up the flash messages from the application view -->
<%= render partial: @login_form %>